USE [forlife-db];
GO

-- 1. LOCAL VENDA
CREATE TABLE TB_LOCALVENDA (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    Descricao VARCHAR(150) NOT NULL,
    Endereco VARCHAR(255) NOT NULL,
    
    CONSTRAINT PK_TB_LOCALVENDA PRIMARY KEY (Id)
);
GO

-- 2. CLIENTE
CREATE TABLE TB_CLIENTE (
    Id INT IDENTITY(1,1) NOT NULL,
    Nome VARCHAR(150) NOT NULL,
    Telefone VARCHAR(20) NOT NULL,
    Dt_Nascimento DATE NULL,
    Email VARCHAR(100) NULL,
    Id_Local UNIQUEIDENTIFIER NOT NULL,

    CONSTRAINT PK_TB_CLIENTE PRIMARY KEY (Id),
    CONSTRAINT FK_TB_CLIENTE_TB_LOCALVENDA FOREIGN KEY (Id_Local) REFERENCES TB_LOCALVENDA (Id)
);
GO

-- 3. VENDA
CREATE TABLE TB_VENDA (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    Id_Cliente INT NOT NULL,
    Data_Venda DATETIME2 NOT NULL DEFAULT GETDATE(), -- Corrigido: Removida a duplicidade
    Valor_Venda DECIMAL(18,2) NOT NULL,
    Status_Venda TINYINT NOT NULL DEFAULT 1,
    Data_Atualizacao DATETIME2 NULL,

    CONSTRAINT PK_TB_VENDA PRIMARY KEY (Id),
    CONSTRAINT FK_TB_VENDA_TB_CLIENTE FOREIGN KEY (Id_Cliente) REFERENCES TB_CLIENTE (Id)
);
GO

-- 4. PAGAMENTO
CREATE TABLE TB_PAGAMENTO (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    Id_Venda UNIQUEIDENTIFIER NOT NULL,
    Num_Parcela INT NOT NULL,
    Status_Pagamento TINYINT NOT NULL DEFAULT 1, -- 1 Pendente, 2 Pago, 3 Replanejada
    Data_Promessa_Pagamento DATETIME2 NOT NULL,
    Data_Pagamento DATETIME2 NULL,
    Valor_Parcela DECIMAL(18,2) NOT NULL,
    Valor_Pago DECIMAL(18,2) NULL,
    Forma_Pagamento VARCHAR(50) NULL,

    CONSTRAINT PK_TB_PAGAMENTO PRIMARY KEY (Id),
    CONSTRAINT FK_TB_PAGAMENTO_TB_VENDA FOREIGN KEY (Id_Venda) REFERENCES TB_VENDA (Id) ON DELETE CASCADE
);
GO

-- 5. PEDIDO PRODUTO
CREATE TABLE TB_PEDIDO_PRODUTO(
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(), -- Corrigido: Adicionada a vírgula que faltava
    Id_Venda UNIQUEIDENTIFIER NOT NULL,
    Id_Produto INT NOT NULL,
    
    CONSTRAINT PK_TB_PEDIDO_PRODUTO PRIMARY KEY (Id),
    CONSTRAINT FK_TB_PEDIDOPRODUTO_TB_VENDA FOREIGN KEY (Id_Venda) REFERENCES TB_VENDA (Id) ON DELETE CASCADE
);
GO